# Generated by Django 4.2.1 on 2023-05-27 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=255)),
                ('textpost', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('video', embed_video.fields.EmbedVideoField(blank=True)),
                ('datepost', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textreply', models.TextField(default='reply')),
                ('replyfrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('replyto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bulletin.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bulletin.category')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bulletin.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='categorypost',
            field=models.ManyToManyField(through='Bulletin.PostCategory', to='Bulletin.category'),
        ),
    ]
